[db]
user = postgres
password =
database = aiida
host = localhost
port = 5432

[local]
data_dir = /data/yadata
engines_dir = /data/yadata/engines
tasks_dir = /data/yadata/tasks
keys_dir = /data/yadata/keys

[engine.pcrystal]
platforms = linux
deploy_local_files = Pcrystal
sleep_interval = 6
platform_packages = openmpi-bin wget
spawn = cp {task_path}/INPUT OUTPUT && mpirun --oversubscribe -np {ncpus} --allow-run-as-root -wd {task_path} {engine_path}/Pcrystal >> OUTPUT 2>&1
check_pname = Pcrystal
input_files = INPUT fort.34
output_files = INPUT fort.34 OUTPUT fort.9 fort.87

[engine.fleur]
platforms = linux
sleep_interval = 6
spawn = cd {task_path} && {engine_path}/fleur_MPI
check_pname = fleur_MPI
input_files = inp.xml
output_files = out.xml inp.xml relax-struct.xsf relax.xml struct.xsf cdn1 juDFT_times.json usage.json
